// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveServiceIDsToday = `-- name: GetActiveServiceIDsToday :many
SELECT service_id FROM calendar
WHERE start_date <= $1::date
  AND end_date >= $1::date
  AND (
    ($2::text = 'monday' AND monday) OR
    ($2::text = 'tuesday' AND tuesday) OR
    ($2::text = 'wednesday' AND wednesday) OR
    ($2::text = 'thursday' AND thursday) OR
    ($2::text = 'friday' AND friday) OR
    ($2::text = 'saturday' AND saturday) OR
    ($2::text = 'sunday' AND sunday)
  )
`

type GetActiveServiceIDsTodayParams struct {
	Today   pgtype.Date `json:"today"`
	Weekday string      `json:"weekday"`
}

func (q *Queries) GetActiveServiceIDsToday(ctx context.Context, arg GetActiveServiceIDsTodayParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getActiveServiceIDsToday, arg.Today, arg.Weekday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var service_id string
		if err := rows.Scan(&service_id); err != nil {
			return nil, err
		}
		items = append(items, service_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCalendar = `-- name: UpsertCalendar :exec
INSERT INTO calendar (service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (service_id) DO UPDATE SET
    monday     = EXCLUDED.monday,
    tuesday    = EXCLUDED.tuesday,
    wednesday  = EXCLUDED.wednesday,
    thursday   = EXCLUDED.thursday,
    friday     = EXCLUDED.friday,
    saturday   = EXCLUDED.saturday,
    sunday     = EXCLUDED.sunday,
    start_date = EXCLUDED.start_date,
    end_date   = EXCLUDED.end_date
`

type UpsertCalendarParams struct {
	ServiceID string      `json:"service_id"`
	Monday    bool        `json:"monday"`
	Tuesday   bool        `json:"tuesday"`
	Wednesday bool        `json:"wednesday"`
	Thursday  bool        `json:"thursday"`
	Friday    bool        `json:"friday"`
	Saturday  bool        `json:"saturday"`
	Sunday    bool        `json:"sunday"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) UpsertCalendar(ctx context.Context, arg UpsertCalendarParams) error {
	_, err := q.db.Exec(ctx, upsertCalendar,
		arg.ServiceID,
		arg.Monday,
		arg.Tuesday,
		arg.Wednesday,
		arg.Thursday,
		arg.Friday,
		arg.Saturday,
		arg.Sunday,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}
