// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package db

import (
	"context"
)

const getFavorite = `-- name: GetFavorite :one
SELECT stop_id FROM favorites WHERE telegram_user_id = $1
`

func (q *Queries) GetFavorite(ctx context.Context, telegramUserID int64) (string, error) {
	row := q.db.QueryRow(ctx, getFavorite, telegramUserID)
	var stop_id string
	err := row.Scan(&stop_id)
	return stop_id, err
}

const upsertFavorite = `-- name: UpsertFavorite :exec
INSERT INTO favorites (telegram_user_id, stop_id, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (telegram_user_id) DO UPDATE SET
    stop_id    = EXCLUDED.stop_id,
    updated_at = now()
`

type UpsertFavoriteParams struct {
	TelegramUserID int64  `json:"telegram_user_id"`
	StopID         string `json:"stop_id"`
}

func (q *Queries) UpsertFavorite(ctx context.Context, arg UpsertFavoriteParams) error {
	_, err := q.db.Exec(ctx, upsertFavorite, arg.TelegramUserID, arg.StopID)
	return err
}
