// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Calendar struct {
	ServiceID string      `json:"service_id"`
	Monday    bool        `json:"monday"`
	Tuesday   bool        `json:"tuesday"`
	Wednesday bool        `json:"wednesday"`
	Thursday  bool        `json:"thursday"`
	Friday    bool        `json:"friday"`
	Saturday  bool        `json:"saturday"`
	Sunday    bool        `json:"sunday"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type EtlCheckpoint struct {
	DatasetName string             `json:"dataset_name"`
	LastSkip    int32              `json:"last_skip"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Route struct {
	RouteID        string  `json:"route_id"`
	RouteShortName string  `json:"route_short_name"`
	RouteLongName  *string `json:"route_long_name"`
	RouteType      *string `json:"route_type"`
}

type Stop struct {
	StopID        string      `json:"stop_id"`
	StopName      string      `json:"stop_name"`
	StopLat       float64     `json:"stop_lat"`
	StopLon       float64     `json:"stop_lon"`
	TransportType *string     `json:"transport_type"`
	Street        *string     `json:"street"`
	Geom          interface{} `json:"geom"`
}

type StopTime struct {
	StopTimesIDRaw string `json:"stop_times_id_raw"`
	TripID         string `json:"trip_id"`
	StopID         string `json:"stop_id"`
	ArrivalTime    string `json:"arrival_time"`
	DepartureTime  string `json:"departure_time"`
	StopSequence   int32  `json:"stop_sequence"`
	GlobalID       int64  `json:"global_id"`
}

type StopTimesStaging struct {
	GlobalID       *int64  `json:"global_id"`
	StopTimesIDRaw *string `json:"stop_times_id_raw"`
	TripID         *string `json:"trip_id"`
	StopID         *string `json:"stop_id"`
	ArrivalTime    *string `json:"arrival_time"`
	DepartureTime  *string `json:"departure_time"`
	StopSequence   *int32  `json:"stop_sequence"`
}

type Trip struct {
	TripID       string  `json:"trip_id"`
	RouteID      string  `json:"route_id"`
	ServiceID    string  `json:"service_id"`
	TripHeadsign *string `json:"trip_headsign"`
	DirectionID  *int16  `json:"direction_id"`
}
