// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	FindNearestStops(ctx context.Context, arg FindNearestStopsParams) ([]FindNearestStopsRow, error)
	GetActiveServiceIDsToday(ctx context.Context, arg GetActiveServiceIDsTodayParams) ([]string, error)
	GetStopByID(ctx context.Context, stopID string) (Stop, error)
	GetUpcomingArrivalsForStop(ctx context.Context, arg GetUpcomingArrivalsForStopParams) ([]GetUpcomingArrivalsForStopRow, error)
	UpsertCalendar(ctx context.Context, arg UpsertCalendarParams) error
	UpsertRoute(ctx context.Context, arg UpsertRouteParams) error
	UpsertStop(ctx context.Context, arg UpsertStopParams) error
	UpsertStopTime(ctx context.Context, arg UpsertStopTimeParams) error
	UpsertTrip(ctx context.Context, arg UpsertTripParams) error
}

var _ Querier = (*Queries)(nil)
