// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error
	// transport_type can hold combined values like "Автобус, Трамвай", so we
	// match with ILIKE rather than equality (see ETL notes on dataset 60662).
	FindNearestStops(ctx context.Context, arg FindNearestStopsParams) ([]FindNearestStopsRow, error)
	GetActiveServiceIDsToday(ctx context.Context, arg GetActiveServiceIDsTodayParams) ([]string, error)
	GetFavorite(ctx context.Context, telegramUserID int64) (string, error)
	GetStopByID(ctx context.Context, stopID string) (Stop, error)
	// arrival_time is stored as TEXT (HH:MM:SS, zero-padded, can exceed 24:00:00
	// for trips spanning midnight per GTFS spec), so lexicographic comparison
	// and ordering work correctly here without casting to a time type.
	GetUpcomingArrivalsForStop(ctx context.Context, arg GetUpcomingArrivalsForStopParams) ([]GetUpcomingArrivalsForStopRow, error)
	ListSubscriptionsForUser(ctx context.Context, telegramUserID int64) ([]ListSubscriptionsForUserRow, error)
	// Case-insensitive substring match on stop_name. Exact matches (after
	// lowercasing) are ranked first, then shorter names (more likely to be
	// what the person meant when they typed a partial name), then alphabetically
	// for stable ordering among ties.
	SearchStopsByName(ctx context.Context, arg SearchStopsByNameParams) ([]SearchStopsByNameRow, error)
	UpsertCalendar(ctx context.Context, arg UpsertCalendarParams) error
	UpsertFavorite(ctx context.Context, arg UpsertFavoriteParams) error
	UpsertRoute(ctx context.Context, arg UpsertRouteParams) error
	UpsertStop(ctx context.Context, arg UpsertStopParams) error
	UpsertStopTime(ctx context.Context, arg UpsertStopTimeParams) error
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error
	UpsertTrip(ctx context.Context, arg UpsertTripParams) error
}

var _ Querier = (*Queries)(nil)
