// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"
)

const upsertRoute = `-- name: UpsertRoute :exec
INSERT INTO routes (route_id, route_short_name, route_long_name, route_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (route_id) DO UPDATE SET
    route_short_name = EXCLUDED.route_short_name,
    route_long_name   = EXCLUDED.route_long_name,
    route_type        = EXCLUDED.route_type
`

type UpsertRouteParams struct {
	RouteID        string  `json:"route_id"`
	RouteShortName string  `json:"route_short_name"`
	RouteLongName  *string `json:"route_long_name"`
	RouteType      *string `json:"route_type"`
}

func (q *Queries) UpsertRoute(ctx context.Context, arg UpsertRouteParams) error {
	_, err := q.db.Exec(ctx, upsertRoute,
		arg.RouteID,
		arg.RouteShortName,
		arg.RouteLongName,
		arg.RouteType,
	)
	return err
}
