// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stop_times.sql

package db

import (
	"context"
)

const getUpcomingArrivalsForStop = `-- name: GetUpcomingArrivalsForStop :many
SELECT
    st.stop_id,
    st.arrival_time,
    st.departure_time,
    r.route_short_name,
    t.trip_headsign,
    t.direction_id
FROM stop_times st
JOIN trips t  ON t.trip_id = st.trip_id
JOIN routes r ON r.route_id = t.route_id
WHERE st.stop_id = $1
  AND t.service_id = ANY($2::text[])
  AND st.arrival_time >= $3
ORDER BY st.arrival_time
LIMIT $4
`

type GetUpcomingArrivalsForStopParams struct {
	StopID           string   `json:"stop_id"`
	ActiveServiceIds []string `json:"active_service_ids"`
	CurrentTimeStr   string   `json:"current_time_str"`
	LimitCount       int32    `json:"limit_count"`
}

type GetUpcomingArrivalsForStopRow struct {
	StopID         string  `json:"stop_id"`
	ArrivalTime    string  `json:"arrival_time"`
	DepartureTime  string  `json:"departure_time"`
	RouteShortName string  `json:"route_short_name"`
	TripHeadsign   *string `json:"trip_headsign"`
	DirectionID    *int16  `json:"direction_id"`
}

// arrival_time is stored as TEXT (HH:MM:SS, zero-padded, can exceed 24:00:00
// for trips spanning midnight per GTFS spec), so lexicographic comparison
// and ordering work correctly here without casting to a time type.
func (q *Queries) GetUpcomingArrivalsForStop(ctx context.Context, arg GetUpcomingArrivalsForStopParams) ([]GetUpcomingArrivalsForStopRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingArrivalsForStop,
		arg.StopID,
		arg.ActiveServiceIds,
		arg.CurrentTimeStr,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingArrivalsForStopRow
	for rows.Next() {
		var i GetUpcomingArrivalsForStopRow
		if err := rows.Scan(
			&i.StopID,
			&i.ArrivalTime,
			&i.DepartureTime,
			&i.RouteShortName,
			&i.TripHeadsign,
			&i.DirectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStopTime = `-- name: UpsertStopTime :exec
INSERT INTO stop_times (global_id, stop_times_id_raw, trip_id, stop_id, arrival_time, departure_time, stop_sequence)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (global_id) DO UPDATE SET
    stop_times_id_raw = EXCLUDED.stop_times_id_raw,
    trip_id            = EXCLUDED.trip_id,
    stop_id             = EXCLUDED.stop_id,
    arrival_time        = EXCLUDED.arrival_time,
    departure_time       = EXCLUDED.departure_time,
    stop_sequence         = EXCLUDED.stop_sequence
`

type UpsertStopTimeParams struct {
	GlobalID       int64  `json:"global_id"`
	StopTimesIDRaw string `json:"stop_times_id_raw"`
	TripID         string `json:"trip_id"`
	StopID         string `json:"stop_id"`
	ArrivalTime    string `json:"arrival_time"`
	DepartureTime  string `json:"departure_time"`
	StopSequence   int32  `json:"stop_sequence"`
}

func (q *Queries) UpsertStopTime(ctx context.Context, arg UpsertStopTimeParams) error {
	_, err := q.db.Exec(ctx, upsertStopTime,
		arg.GlobalID,
		arg.StopTimesIDRaw,
		arg.TripID,
		arg.StopID,
		arg.ArrivalTime,
		arg.DepartureTime,
		arg.StopSequence,
	)
	return err
}
