// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stops.sql

package db

import (
	"context"
)

const findNearestStops = `-- name: FindNearestStops :many
SELECT
    stop_id,
    stop_name,
    stop_lat,
    stop_lon,
    transport_type,
    street,
    ST_Distance(geom, ST_MakePoint($1::float8, $2::float8)::geography) AS distance_meters
FROM stops
WHERE transport_type = 'Автобус'
ORDER BY geom <-> ST_MakePoint($1::float8, $2::float8)::geography
LIMIT $3
`

type FindNearestStopsParams struct {
	Lon        float64 `json:"lon"`
	Lat        float64 `json:"lat"`
	LimitCount int32   `json:"limit_count"`
}

type FindNearestStopsRow struct {
	StopID         string      `json:"stop_id"`
	StopName       string      `json:"stop_name"`
	StopLat        float64     `json:"stop_lat"`
	StopLon        float64     `json:"stop_lon"`
	TransportType  *string     `json:"transport_type"`
	Street         *string     `json:"street"`
	DistanceMeters interface{} `json:"distance_meters"`
}

func (q *Queries) FindNearestStops(ctx context.Context, arg FindNearestStopsParams) ([]FindNearestStopsRow, error) {
	rows, err := q.db.Query(ctx, findNearestStops, arg.Lon, arg.Lat, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNearestStopsRow
	for rows.Next() {
		var i FindNearestStopsRow
		if err := rows.Scan(
			&i.StopID,
			&i.StopName,
			&i.StopLat,
			&i.StopLon,
			&i.TransportType,
			&i.Street,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStopByID = `-- name: GetStopByID :one
SELECT stop_id, stop_name, stop_lat, stop_lon, transport_type, street, geom FROM stops WHERE stop_id = $1
`

func (q *Queries) GetStopByID(ctx context.Context, stopID string) (Stop, error) {
	row := q.db.QueryRow(ctx, getStopByID, stopID)
	var i Stop
	err := row.Scan(
		&i.StopID,
		&i.StopName,
		&i.StopLat,
		&i.StopLon,
		&i.TransportType,
		&i.Street,
		&i.Geom,
	)
	return i, err
}

const upsertStop = `-- name: UpsertStop :exec
INSERT INTO stops (stop_id, stop_name, stop_lat, stop_lon, transport_type, street)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (stop_id) DO UPDATE SET
    stop_name      = EXCLUDED.stop_name,
    stop_lat       = EXCLUDED.stop_lat,
    stop_lon       = EXCLUDED.stop_lon,
    transport_type = EXCLUDED.transport_type,
    street         = EXCLUDED.street
`

type UpsertStopParams struct {
	StopID        string  `json:"stop_id"`
	StopName      string  `json:"stop_name"`
	StopLat       float64 `json:"stop_lat"`
	StopLon       float64 `json:"stop_lon"`
	TransportType *string `json:"transport_type"`
	Street        *string `json:"street"`
}

func (q *Queries) UpsertStop(ctx context.Context, arg UpsertStopParams) error {
	_, err := q.db.Exec(ctx, upsertStop,
		arg.StopID,
		arg.StopName,
		arg.StopLat,
		arg.StopLon,
		arg.TransportType,
		arg.Street,
	)
	return err
}
