// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"
)

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE telegram_user_id = $1 AND stop_id = $2 AND route_id = $3
`

type DeleteSubscriptionParams struct {
	TelegramUserID int64  `json:"telegram_user_id"`
	StopID         string `json:"stop_id"`
	RouteID        string `json:"route_id"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.TelegramUserID, arg.StopID, arg.RouteID)
	return err
}

const listSubscriptionsForUser = `-- name: ListSubscriptionsForUser :many
SELECT
    s.stop_id,
    st.stop_name,
    s.route_id,
    r.route_short_name
FROM subscriptions s
JOIN stops st  ON st.stop_id = s.stop_id
JOIN routes r  ON r.route_id = s.route_id
WHERE s.telegram_user_id = $1
ORDER BY st.stop_name, r.route_short_name
`

type ListSubscriptionsForUserRow struct {
	StopID         string `json:"stop_id"`
	StopName       string `json:"stop_name"`
	RouteID        string `json:"route_id"`
	RouteShortName string `json:"route_short_name"`
}

func (q *Queries) ListSubscriptionsForUser(ctx context.Context, telegramUserID int64) ([]ListSubscriptionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForUser, telegramUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsForUserRow
	for rows.Next() {
		var i ListSubscriptionsForUserRow
		if err := rows.Scan(
			&i.StopID,
			&i.StopName,
			&i.RouteID,
			&i.RouteShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (telegram_user_id, stop_id, route_id)
VALUES ($1, $2, $3)
ON CONFLICT (telegram_user_id, stop_id, route_id) DO NOTHING
`

type UpsertSubscriptionParams struct {
	TelegramUserID int64  `json:"telegram_user_id"`
	StopID         string `json:"stop_id"`
	RouteID        string `json:"route_id"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription, arg.TelegramUserID, arg.StopID, arg.RouteID)
	return err
}
