// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package db

import (
	"context"
)

const upsertTrip = `-- name: UpsertTrip :exec
INSERT INTO trips (trip_id, route_id, service_id, trip_headsign, direction_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (trip_id) DO UPDATE SET
    route_id       = EXCLUDED.route_id,
    service_id     = EXCLUDED.service_id,
    trip_headsign  = EXCLUDED.trip_headsign,
    direction_id   = EXCLUDED.direction_id
`

type UpsertTripParams struct {
	TripID       string  `json:"trip_id"`
	RouteID      string  `json:"route_id"`
	ServiceID    string  `json:"service_id"`
	TripHeadsign *string `json:"trip_headsign"`
	DirectionID  *int16  `json:"direction_id"`
}

func (q *Queries) UpsertTrip(ctx context.Context, arg UpsertTripParams) error {
	_, err := q.db.Exec(ctx, upsertTrip,
		arg.TripID,
		arg.RouteID,
		arg.ServiceID,
		arg.TripHeadsign,
		arg.DirectionID,
	)
	return err
}
